{"name": "test_csv_file", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../data/test.csv'", "trace": "def test_csv_file():\n        # with open('../data/test.csv', 'r') as fp:\n        #     data = []\n        #     try:\n        #         reader = csv.reader(fp)\n        #         headers = next(reader)\n        #         for row in reader:\n        #             data.append(row)\n        #     except Exception as e:\n        #         print('Exception is %s'%e)\n        #     finally:\n        #         fp.close()\n>       data = get_csv_datas()\n\ntest/test_file.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \ncommon/get_csv_data.py:22: in get_csv_datas\n    datas = get_csv_data('../data/test.csv')\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nfilePath = '../data/test.csv'\n\n    def get_csv_data(filePath):\n>       with open(filePath, 'r') as fp:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../data/test.csv'\n\ncommon/get_csv_data.py:5: FileNotFoundError"}, "start": 1618405037422, "stop": 1618405037423, "uuid": "64261923-7338-40c6-ad39-68fc416570dc", "historyId": "6940d229a246b5b81b594da3ef961d54", "testCaseId": "7f0e4a87f6b896889d8228cd4f04373d", "fullName": "test.test_file#test_csv_file", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_file"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "17623-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_file"}]}