{"name": "test_secure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "@pytest.mark.secure\n    def test_secure():\n        print(\"secure test\")\n>       assert 2!=2\nE       assert 2 != 2\n\ntest/test_mark.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "cb57959f-ff41-4c00-a82c-ade9e115a706-attachment.txt", "type": "text/plain"}], "start": 1617978256762, "stop": 1617978256762, "uuid": "493bb4bd-0ae7-4e8c-8188-8a71d5286c94", "historyId": "02c5799b51eb79bb05e5b8766edaf2c6", "testCaseId": "44201fe38198292e8496495a8062a999", "fullName": "test.test_mark#test_secure", "labels": [{"name": "tag", "value": "secure"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_mark"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "92712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_mark"}]}