{"name": "test_secure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "@pytest.mark.secure\n    def test_secure():\n        print(\"secure test\")\n>       assert 2!=2\nE       assert 2 != 2\n\ntest/test_mark.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "2a539dbf-62a6-40d7-8853-605924348b1b-attachment.txt", "type": "text/plain"}], "start": 1618405179511, "stop": 1618405179511, "uuid": "bf68ffb9-2cd3-4174-9f68-b8ee17e6b44b", "historyId": "02c5799b51eb79bb05e5b8766edaf2c6", "testCaseId": "44201fe38198292e8496495a8062a999", "fullName": "test.test_mark#test_secure", "labels": [{"name": "tag", "value": "secure"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_mark"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "17948-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_mark"}]}