{"name": "test_C", "status": "skipped", "statusDetails": {"message": "XFAIL reason: 将用例定义为xfail，后续不会执行。\n\n_pytest.outcomes.XFailed: 将用例定义为xfail，后续不会执行。", "trace": "def test_C():\n>       pytest.xfail(reason='将用例定义为xfail，后续不会执行。')\nE       _pytest.outcomes.XFailed: 将用例定义为xfail，后续不会执行。\n\ntest/test_demo.py:36: XFailed"}, "start": 1618405200224, "stop": 1618405200225, "uuid": "8e6fade7-3f81-46e1-ab0e-a523292d39d7", "historyId": "bc5a1df9c37f145ff3d00f63f05b60d0", "testCaseId": "259e1ac4a16f16936beef17a75312446", "fullName": "test.test_demo#test_C", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_demo"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "18026-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_demo"}]}