{"name": "test_secure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 != 2", "trace": "@pytest.mark.secure\n    def test_secure():\n        print(\"secure test\")\n>       assert 2!=2\nE       assert 2 != 2\n\ntest/test_mark.py:25: AssertionError"}, "attachments": [{"name": "stdout", "source": "7363c7ae-72a6-4f93-9d17-cf01b0d81fed-attachment.txt", "type": "text/plain"}], "start": 1618405323154, "stop": 1618405323154, "uuid": "3cd80fb1-28cf-4766-8ab9-dd9efed31313", "historyId": "02c5799b51eb79bb05e5b8766edaf2c6", "testCaseId": "44201fe38198292e8496495a8062a999", "fullName": "test.test_mark#test_secure", "labels": [{"name": "tag", "value": "secure"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_mark"}, {"name": "host", "value": "avivatangdeMacBook-Pro.local"}, {"name": "thread", "value": "18417-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_mark"}]}